name: Package exe with PyInstaller - Macbook M1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
       shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: launcher
        path: src/dist/windows # or path/to/artifact

